import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchResults } from './searchAPI';

const initialState = {
  value: [],
  status: 'idle',
};



// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getResults2 = createAsyncThunk(
  'search/fetchResults',
  async (query) => {
    const response = await fetchResults(query);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const searchSlice = createSlice({
  name: 'search',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    getResults: (state, action) => {
      fetchResults(action.payload).then(results => {
        console.log(results)
        state.value = results
      })
    },
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getResults2.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getResults2.fulfilled, (state, action) => {
        state.status = 'idle';
        console.log(action.payload)
        state.value = action.payload;
      });
  },

});

export const { getResults } = searchSlice.actions;

export const selectResults = (state) => state.search.value;

export default searchSlice.reducer;
