import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import {
  fetchPrepositions,
  fetchPrepositionsByMedia
} from './prepositionsAPI';

const initialState = {
  prepositions: [],
  status: 'idle'
};



// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getPrepositions = createAsyncThunk(
  'media/fetchPrepositions',
  async (language) => {
    const response = await fetchPrepositions(language);
    // The value we return becomes the `fulfilled` action payload
    return response.data || [];
  }
);

export const getPrepositionsByMedia = createAsyncThunk(
  'media/fetchPrepositionsByMedia',
  async (media) => {
    const response = await fetchPrepositionsByMedia(media);
    // The value we return becomes the `fulfilled` action payload
    return response.data || [];
  }
);

export const prepositionsSlice = createSlice({
  name: 'prepositions',
  initialState,

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getPrepositions.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getPrepositions.fulfilled, (state, action) => {
        state.status = 'idle';
        state.prepositions = action.payload.prepositions.sort();
      })
      .addCase(getPrepositionsByMedia.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getPrepositionsByMedia.fulfilled, (state, action) => {
        state.status = 'idle';
        state.prepositions = action.payload.prepositions.sort();
      })
  },

});

export const selectPrepositions = (state) => state.prepositions.prepositions;
export const selectPrepositionsByMedia = (state) => state.prepositions.prepositions;
export default prepositionsSlice.reducer;
