import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import {
  fetchConjugations
} from './verbAPI';

const initialState = {
  conjugations: [],
  status: 'idle',
};



// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

export const getConjugations = createAsyncThunk(
  'conjugation/fetchConjugations',
  async (tense_verb) => {
    const [tense, verb] = tense_verb
    const response = await fetchConjugations(tense, verb);
    // The value we return becomes the `fulfilled` action payload
    return response.data
  }
);

export const verbSlice = createSlice({
  name: 'verb',
  initialState,

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getConjugations.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getConjugations.fulfilled, (state, action) => {
        state.status = 'idle';
        state.conjugations = action.payload;
      })
  },

});

export const selectConjugations = (state) => state.verb.conjugations;
export default verbSlice.reducer;
